### ISSUE TITLE
Expand GitHub actions integration

### ISSUE THREAD

**Issue by trannel** [gipplab/NLP-Land-frontend#18]
**Is your feature request related to a problem? Please describe.**
Currently this repository does not use any GitHub actions workflows besides a deploy script. It would be nice if the workflows from the [backend](https://github.com/ag-gipp/NLP-Land-backend/tree/main/.github) or [NLPLand](https://github.com/ag-gipp/NLPLand/tree/main/.github) could also be implemented here.

**Describe the solution you'd like**
- [x] ~~Implement workflow to create issues branches~~ Use the `Create a branch` function on the right panel of the issue under `Development` instead
- [x] Implement pull request workflow for unit tests, typing, linting, and automatic documentation.
- [x] Implement workflow that creates releases and deploys them (deploy main branch to firebase-dev, deploy releases to firebase)
- [x] Add/fix all badges in the README

**Describe alternatives you've considered**
Copying everything from the backend or NLPLand repository might also work.
👆🏻 This is probably the preferred solution to avoid work 👆🏻

**Additional context**
Related to https://github.com/ag-gipp/NLP-Land-frontend/issues/4

**Comment by jpelhaW** [comment]
Unter `Development` on the right panel of an issue, GitHub now has the functionality to create a branch. We might just use that.

**Comment by trannel** [comment]
Sure, let's use that. Should we keep our format from the backend, e.g. `issue-9`, or name them as GitHub proposes, e.g. `9-add-filters`?

**Comment by jpelhaW** [comment]
Just use the GitHub standard then. 👍
