### ISSUE TITLE
Add release version and Icon with Link to GitHub on the frontend page

### ISSUE THREAD

**Issue by jpelhaW** [gipplab/NLP-Land-frontend#5]
**Is your feature request related to a problem? Please describe.**
To keep track of which version of the frontend we are serving we should display the release number on the frontend page.
Also, a link to GitHub would be nice for people to check out the repo and contribute.

**Describe the solution you'd like**
Add both on all pages, e.g. in the header or footer.

**Describe alternatives you've considered**
Add only on the main page.

**Comment by trannel** [comment]
Added in #39
